### ISSUE TITLE
debug mode failed to start

### ISSUE THREAD

**Issue by marksilinio** [marksilinio/isp-data-noize#5]
```
/isp_data_pollution.py -g
This is ISP Data Pollution 🐙💨, Version 2.0.1
Traceback (most recent call last):
  File "/home/kali/src/isp-data-pollution/./isp_data_pollution.py", line 1133, in <module>
    ISPDataPollution()
  File "/home/kali/src/isp-data-pollution/./isp_data_pollution.py", line 243, in __init__
    self.check_chromedriver_version()
  File "/home/kali/src/isp-data-pollution/./isp_data_pollution.py", line 277, in check_chromedriver_version
    self.driver.capabilities["version"],
KeyError: 'version'
```

**Comment by marksilinio** [comment]
https://github.com/essandess/isp-data-pollution/issues/33
